### ISSUE TITLE
module search not wokring

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [WithSecureLabs/drozer-agent#20] opened 2024-10-15 10:27 UTC
After install drozer 3.1 from PIP and drozer-agent.apk on AVD with API 28, I connected using:

```
adb forward tcp:31415 tcp:31415
drozer console connect --server localhost:31415
```

When I run:

`dz> module search`

Drozer stops with error:

```
Loop exception
Exception occured: no element found: line 1, column 0
```

**Comment by cyberMilosz** [comment] 2024-10-21 11:01
console bug, duplicate of https://github.com/WithSecureLabs/drozer/issues/467

**Closed by cyberMilosz** 2024-10-21 11:01 UTC
